### ISSUE TITLE
Python Trace Errors

### ISSUE THREAD

**Issue by jean1880** [jyapayne/Web2Executable#118]
When attempting to use NodeWebkit v0.13.0-beta4 get python errors:
```
INFO       2016-02-06 01:48:08,206 command_line.py: 400 get_versions - Getting versions...
INFO       2016-02-06 01:48:14,172 command_line.py: 465 load_package_json - Loading package.json
INFO       2016-02-06 01:48:14,172 command_line.py: 465 load_package_json - Loading package.json
INFO       2016-02-06 01:48:29,007 command_line.py: 900 copy_files_to_project_folder - Copying files to C:\Users\Jean-Luc\Documents\github\Orion\App\DogTool\dist
INFO       2016-02-06 01:48:29,023 command_line.py: 487 generate_json - Generating package.json...
INFO       2016-02-06 01:48:29,023 command_line.py: 487 generate_json - Generating package.json...
DEBUG      2016-02-06 01:48:31,108 PngImagePlugin.py: 135 call - STREAM b'IHDR' 16 13
DEBUG      2016-02-06 01:48:31,108 PngImagePlugin.py: 135 call - STREAM b'pHYs' 41 9
DEBUG      2016-02-06 01:48:31,108 PngImagePlugin.py: 135 call - STREAM b'iCCP' 62 2639
DEBUG      2016-02-06 01:48:31,124 PngImagePlugin.py: 298 chunk_iCCP - iCCP profile name b'Photoshop ICC profile'
DEBUG      2016-02-06 01:48:31,124 PngImagePlugin.py: 299 chunk_iCCP - Compression method 0
DEBUG      2016-02-06 01:48:31,124 PngImagePlugin.py: 135 call - STREAM b'cHRM' 2713 32
DEBUG      2016-02-06 01:48:31,124 PngImagePlugin.py: 511 _open - b'cHRM' 2713 32 (unknown)
DEBUG      2016-02-06 01:48:31,124 PngImagePlugin.py: 135 call - STREAM b'IDAT' 2757 1939734
ERROR      2016-02-06 01:48:31,124 command_line.py: 805 make_output_dirs - Traceback (most recent call last):
  File "site-packages\PIL\ImageFile.py", line 460, in _save
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "command_line.py", line 777, in make_output_dirs
  File "command_line.py", line 651, in replace_icon_in_exe
  File "pepy\pe.py", line 1254, in replace_icon
  File "pepy\pe.py", line 18, in resize
  File "site-packages\PIL\Image.py", line 1675, in save
  File "pepy\ico_plugin.py", line 306, in _save
  File "site-packages\PIL\Image.py", line 1675, in save
  File "pepy\bmpimageplugin.py", line 317, in _save
  File "site-packages\PIL\ImageFile.py", line 468, in _save
SystemError: tile cannot extend outside image
```

Was able to have exporter work without a window icon (the image used works for v0.12x) however, the exported content appears to be the default NodeWebkit files with no content from the source folder

**Comment by jyapayne** [comment]
If you are running from source, you'll have to install the latest version of PIL, since that issue was fixed in 3.0.0 as seen [here](http://stackoverflow.com/questions/33285330/unsupportedoperation-fileno-how-to-fix-this-python-dependency-mess).

However, there is a separate issue that I found while debugging your issue. I was able to get past the fileno error, but I got an error with the icon replacement. I just pushed a change that fixes that issue, so the icon replacement will work.

However, NW.js 0.13.0-betaX does not currently work with Web2Exe, since it does not support adding the nw.app file to the end of the file any more. You could use [nw-builder](https://github.com/nwjs/nw-builder) instead, which was built by the NW.js team, as recommended [here](http://docs.nwjs.io/en/v0.13.0-beta5/For%20Users/Package%20and%20Distribute/#quick-start).

**Comment by Yutna** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/11186504/12919453/b3eb5376-cf76-11e5-860a-4bf0582b9375.png)

I got this errors when I use Web2exe GUI. (It look like this issue) I use nw.js v0.12.3 for my app. How to solve this problem? Sorry for my English.

**Comment by jyapayne** [comment]
@Yutna that is a separate issue, but I believe I fixed it in the [newest version](https://github.com/jyapayne/Web2Executable/releases/tag/v0.4.2b). Please try it out :)

**Comment by jyapayne** [comment]
Closing due to inactivity. Reopen if the issue persists in the latest version.
