### ISSUE TITLE
Output empty when Exe Icon/Window Icon fill with png icon

### ISSUE THREAD

**Issue by aegin** [jyapayne/Web2Executable#123]
Hi Jyapayne, thanks for your web2executable tool.
I tried using version 0.4.3b for Windows, then i fill in the Exe Icon field with 48 Pixel png icon, after export my app not found except nw.exe.
I tried with blank Exe icon field then app can created..
whats wrong with my png icon..? thanks.

**Comment by jyapayne** [comment]
Hmm, interesting. This issue seems to keep popping up. What is your Windows version? Also, can you post the contents of the error log here? (Located at C:\Users\<username>\AppData\Local\Web2Executable\Web2Executable\files)

**Comment by aegin** [comment]
i use windows 8 operating system and error log shown bellow.. 
.....
Error recieved: [WinError 5] Access is denied: '\\\\?\\H:\\Web2ExeWin\\test\\output\\test'
Copying files to H:\Web2ExeWin\test
INFO       2016-03-22 23:42:23,513 command_line.py: 942 copy_files_to_project_folder - Copying files to H:\Web2ExeWin\test
Generating package.json...
INFO       2016-03-22 23:42:23,513 command_line.py: 490 generate_json - Generating package.json...
Generating package.json...
INFO       2016-03-22 23:42:23,545 command_line.py: 490 generate_json - Generating package.json...
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 135 call - STREAM b'IHDR' 16 13
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 135 call - STREAM b'gAMA' 41 4
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 135 call - STREAM b'cHRM' 57 32
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 511 _open - b'cHRM' 57 32 (unknown)
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 135 call - STREAM b'bKGD' 101 6
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 511 _open - b'bKGD' 101 6 (unknown)
DEBUG      2016-03-22 23:42:32,798 PngImagePlugin.py: 135 call - STREAM b'IDAT' 119 14148
Traceback (most recent call last):
  File "command_line.py", line 811, in make_output_dirs
  File "command_line.py", line 670, in replace_icon_in_exe
  File "pepy\pe.py", line 1321, in write
PermissionError: [Errno 13] Permission denied: 'H:\\Web2ExeWin\\test\\output\\test\\windows-x32\\nw.exe'
......

**Comment by jyapayne** [comment]
Ah, that looks like a known issue with permissions. I currently don't know why this happens, and have not been able to reproduce it on my test machines. A workaround is to delete the output folder each time manually (which is obviously not ideal). Also, make sure the permissions to the H:\Web2ExeWin\ folder allow writes, even though they probably do since you were able to get a successful export at least once.

**Comment by hitaloramon** [comment]
I'm also having this same problem
