### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode  --help command

### ISSUE THREAD

**Issue by Arti3DPlayer** [jyapayne/Web2Executable#184]
Run
`./web2exe-linux --help` and get:

```
Traceback (most recent call last):
  File "command_line.py", line 1699, in <module>
  File "command_line.py", line 1685, in main
  File "command_line.py", line 1537, in get_arguments
  File "argparse.py", line 1726, in parse_args
  File "argparse.py", line 1758, in parse_known_args
  File "argparse.py", line 1964, in _parse_known_args
  File "argparse.py", line 1904, in consume_optional
  File "argparse.py", line 1832, in take_action
  File "argparse.py", line 1014, in __call__
  File "argparse.py", line 2357, in print_help
  File "argparse.py", line 2363, in _print_message
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 4284: ordinal not in range(128)
Failed to execute script command_line
```

**Comment by jyapayne** [comment]
@Arti3DPlayer That usually means your terminal doesn't support unicode characters or is in a mode that doesn't support unicode characters. What terminal are you using?

**Comment by Arti3DPlayer** [comment]
@jyapayne yes, i think you are right, need to update locale settings
