### ISSUE TITLE
Errors when choosing project

### ISSUE THREAD

**Issue by purecreative** [jyapayne/Web2Executable#54]
When I choose my project from the browser everything stays greyed out.

in the error log I get:

```
Traceback (most recent call last):
  File "<string>", line 757, in browse_dir
  File "<string>", line 762, in load_project
  File "<string>", line 95, in save_recent_project
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0192' in position 42: ordinal not in range(128)

ERROR      2015-05-07 13:52:34,813 command_line.py: 67 my_excepthook - Traceback (most recent call last):
  File "<string>", line 757, in browse_dir
  File "<string>", line 762, in load_project
  File "<string>", line 95, in save_recent_project
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0192' in position 42: ordinal not in range(128)
```

**Comment by jyapayne** [comment]
Looks like you have some Unicode characters in your project. I think I can add Unicode support. I'll try to add it for the next build.

**Comment by jyapayne** [comment]
I put the fix in the latest build, so it should fix the issue.
