### ISSUE TITLE
Can't not run web2exe (version 0.2.4b) on Ubuntu Linux 14.04 (Error: No module named appdirs)

### ISSUE THREAD

**Issue by Yutna** [jyapayne/Web2Executable#77]
I try to run Web2Exe on CLI. but I get this in my terminal, How to fix it? (sorry for my english)
```
yutthana@xxx-PC:~/MyFiles/Programs/Web2Executable/Web2ExeLinux$ python --version
Python 2.7.6
yutthana@xxx-PC:~/MyFiles/Programs/Web2Executable/Web2ExeLinux$ ./web2exe 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_7616097-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/joey/Projects/Web2Executable/build/web2exe/out00-PYZ.pyz/utils", line 5, in <module>
ImportError: No module named appdirs
```

**Comment by jyapayne** [comment]
Hmm, that's odd. The dependencies should be included. You could install pip and then do a `pip install appdirs` command to see if it helps. I'll look into why this is happening.

**Comment by kamaldeepoodles** [comment]
Please track this error also

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from PySide import QtGui, QtCore
ImportError: No module named PySide

**Comment by Yutna** [comment]
@jyapayne  I installed pip and ran this command.
```
sudo apt-get install python-pipe
pip install appdirs
```

I got this error
```
Downloading/unpacking appdirs
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Installing collected packages: appdirs
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/appdirs-1.4.0.dist-info'

Storing debug log for failure in /home/yutthana/.pip/pip.log

```

I am not familiar with the python programming language. I don't known the error what does it mean.
Sorry for my English.

**Comment by jyapayne** [comment]
@Yutna, you must run the command as root: sudo pip install appdirs.

@kamaldeepnoodles, you have to install the requirements. Run: sudo pip install -r requirements.txt 

Note that you also need to install Qt if you are running using Python.

**Comment by jyapayne** [comment]
Did any of this help?

**Comment by Yutna** [comment]
I typed this command
```
sudo pip install appdirs
```
I got this message
```
Requirement already satisfied (use --upgrade to upgrade): appdirs in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

I try to re-ren web2exe (2.4b) again
```
./web2exe
```

I got this message 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_7616097-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/joey/Projects/Web2Executable/build/web2exe/out00-PYZ.pyz/utils", line 5, in <module>
ImportError: No module named appdirs

```

I don't known why i can't run. I back to use v0.2.3b to build my production files. Thank you for your help

**Comment by jyapayne** [comment]
I've recompiled the binary. Does this work for you?

http://www.mediafire.com/download/seuu5bnwhc8dbd4/Web2ExeLinux-v0.2.5b.zip

**Comment by Yutna** [comment]
@jyapayne v0.2.5b ok it's work!! thank you
